controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true
    
    mecanum_cont:
      type: mecanum_drive_controller/MecanumDriveController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

mecanum_cont:
  ros__parameters:
    # Command joint names
    front_left_wheel_command_joint_name: "wheel_joint_fl"
    front_right_wheel_command_joint_name: "wheel_joint_fr"
    rear_left_wheel_command_joint_name: "wheel_joint_bl"
    rear_right_wheel_command_joint_name: "wheel_joint_br"


    front_left_wheel_state_joint_name: "wheel_joint_fl"
    front_right_wheel_state_joint_name: "wheel_joint_fr"
    rear_left_wheel_state_joint_name: "wheel_joint_bl"
    rear_right_wheel_state_joint_name: "wheel_joint_br"
    
    # Kinematics
    kinematics:
      base_frame_offset: { x: 0.0, y: 0.0, theta: 0.0 }
      wheels_radius: 0.05
      sum_of_robot_center_projection_on_X_Y_axis: 0.386
    
    # Frame IDs
    base_frame_id: "base_link"
    # CRITICAL: Enable odom TF publishing
    odom_frame_id: "odom"
    enable_odom_tf: true

    
    
    # Timeout
    reference_timeout: 0.9
    
    # Covariances
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

joint_broad:
  ros__parameters:
    use_local_topics: false