controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 20
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    gripper_action_controller:
      type: position_controllers/GripperActionController 

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true

joint_trajectory_controller:
  ros__parameters:
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      arm_joint_1:
        trajectory: 0.05
        goal: 0.03
      arm_joint_2:
        trajectory: 0.05
        goal: 0.03
      arm_joint_3:
        trajectory: 0.05
        goal: 0.03
      arm_joint_4:
        trajectory: 0.05
        goal: 0.03
      arm_joint_5:
        trajectory: 0.05
        goal: 0.03

gripper_action_controller:
  ros__parameters:
    use_sim_time: true
    joint: gripper_finger_joint_l
    action_monitor_rate: 20.0
    goal_tolerance: 0.01
    max_effort: 20.0
    allow_stalling: false
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0